### ISSUE TITLE
Question about constants.py 

### ISSUE THREAD

**Issue by rnrson9** [neu-nds2/cyber-resilience#1]
I didn't find the file named constants.py , is it a python package or created by yourself. Could you please tell me how to create it?

![image](https://user-images.githubusercontent.com/59202004/230700064-c443cb4f-da40-454f-9a5b-9e307f274e38.png)

**Comment by neu-nds2** [comment]
It is a file created by myself, sorry I forgot to upload it. It just contains the path to the data directory. I added it now. Thank you.
